export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const ADD_NOMINATION = "ADD_NOMINATION";
export const REMOVE_NOMINATION = "REMOVE_NOMINATION";
export const REMOVE_ALL_NOMINATION = "REMOVE_ALL_NOMINATION";
export const MOVIE_ERROR = "MOVIE_ERROR";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const REFRESH_LOCAL_STORAGE = "REFRESH_LOCAL_STORAGE";
export const LOAD_NOMINATED_MOVIES = "LOAD_NOMINATED_MOVIES";
export const LOAD_NOMINATED_MOVIES_ERROR = "LOAD_NOMINATED_MOVIES_ERROR";